### ISSUE TITLE
Control flow graph

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#1]
Cretonne's in-memory representation needs a control flow graph analysis. This would record for each EBB:

- A set of predecessors, where a predecessor is an (EBB, Inst) pair identifying a basic block in an EBB.
- A set of successor EBBs. This may not be worthwhile caching since it is easily derived from the branch instructions in the EBB.

The control flow graph is easily computed from the code, so we don't want to represent it in the textual IR. It would be useful if the iteration order of the predecessor set were stable so it doesn't change when saving out the IR and reloading it.

**Comment by mrrrgn** [comment]
A very ugly WIP. https://github.com/mrrrgn/cretonne/commit/19ef16e508df28b916cb8a45490368dd58bfaeff

todo:
  - Code cleanup and restructuring (maybe the predecessors should be stored on the Function?)
  - Tests!
  - Generating prettier graphviz graphs.

**Comment by mrrrgn** [comment]
A new approach which moves the CFG into its own data structure. This is tidier and easier to test IMO. Speaking of tests, writing them now. https://github.com/mrrrgn/cretonne/commit/977d11046dcb4383f59a4d3bc9e9a448dbe28c65

The graph printing is still ugly/basic. Thinking about the parser interface as I proceed with that.

**Comment by mrrrgn** [comment]
https://github.com/stoklund/cretonne/pull/6
https://github.com/stoklund/cretonne/pull/7

**Comment by mrrrgn** [comment]
Let's add some tests for the `print-cfg` command before closing this.

**Comment by mrrrgn** [comment]
https://github.com/stoklund/cretonne/pull/8
