### ISSUE TITLE
Long function names don't render correctly

### ISSUE THREAD

**Issue by denismerigoux** [stoklund/cretonne#100]
Functions with names whose character count is higher than `funcname::NAME_LENGTH_THRESHOLD` (22) are not displayed properly: `#6933322e6e6f5f666f6c645f636d705f735f6f6666736574` instead of `i32.no_fold_cmp_s_offset` (this string has 23 characters).

The bug should be in `funcname::try_as_name`.

**Comment by stoklund** [comment]
Function names are printed as text if they consist of alphanumerical characters and `_`. The `.` in the name would cause it to be printed as hex.

**Comment by denismerigoux** [comment]
OK, so this is not an issue. Thanks!
