### ISSUE TITLE
Verifier complaining about variable uses in unreachable code

### ISSUE THREAD

**Issue by denismerigoux** [stoklund/cretonne#108]
As of now, the verifier yields an error when, while checking unreachable code, it detects the use of a variable defined in reachable code. This error is not relevant and the corresponding check should just be removed in the case of unreachable code.

**Comment by stoklund** [comment]
Yep, skip dominance checks in unreachable code.

Mathematically:

> A dominates B iff all paths from the entry block to B pass through A.

If B is unreachable, all paths from the entry block to B go through A for any A (since there are no such paths).
