### ISSUE TITLE
Add WiderThan constraint

### ISSUE THREAD

**Issue by d1m0** [stoklund/cretonne#114]
Instructions such as sextend, uextend and ireduce require a type constraint between the widths of the argument and the result value. One way to implement this is to:

- Add a ConstrainWiderThan TypeConstraint in ti.py
- Extend Instruction constructors to allow for constraints amongst formal vars
- Add the instruction specific constraints to the constraints accumulated by typeinference.

~Dimo

**Comment by stoklund** [comment]
This sounds good to me. Also consider the constraints for the `bitcast` instruction. It needs the input and output types to be of the same size, but they are not required to have the same number of vector lanes.
