### ISSUE TITLE
Cleanup for PR #123 - Semantics

### ISSUE THREAD

**Issue by d1m0** [stoklund/cretonne#124]
Comments that need to be addressed:

- T = MTypeVar('T') in cdsl/ti.py is unused
- in semantics of iadd_cin and iadd_carry should use bvsignext instead of bvzeroext on c_in.
- Use explicit z3 bindings for smtlib.py (z3 becomes a proof dependency)

**Comment by stoklund** [comment]
The second one doesn't sound right.

I was taking about the representation of `b32` and `b64` etc. They have all-zero or all-one bits.

**Comment by d1m0** [comment]
Sorry, I misread your PR comment. Yes, the second should read: the semantics of bextend should use bvsignext instead of bvzeroext
