### ISSUE TITLE
Test compressed encodings

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#128]
The `test binemit` file tests currently check against the first valid encoding of each instruction. These are the encodings that the register allocator sees.

It would also be good to test the compressed instruction encodings that will be generated when #72 is implemented.

Since there are other ways of testing the early instruction selection by the legalizer, it would make sense to change the `test binemit` driver to pick the smallest valid instruction encoding which:

1. Satisfies all instruction and ISA predicates. (This is already checked by `TargetIsa::legal_encodings()`).
2. Has satisfied register constraints given the register assignments in the test file.
3. Has satisfied branch range constraints. (See the `binemit/relaxation.rs` pass).

Some of the Intel 64-bit encoding tests would need to be changed since they contain redundant REX prefixes. See comments on #127.

**Comment by angusholder** [comment]
I'm going to tackle this before writing tests for #160, you mentioned in #127 that you'd like to be able to test two forms of encodings like so:

    ; asm: movl %ecx, (%rsi)
    istore32 v1, v2                             ; bin[early]: 40 89 0e
                                                ; bin[late]:  89 0e

Should I go the full way and implement that? Should I just make plain `bin:` directives accept any of the legal encodings? Should this be a separate PR from #160?

**Comment by stoklund** [comment]
We have an `is_compressed` setting that I think you can use to control this. When `is_compressed=0` the `binemit` tests should check the default encoding like they do today. When `is_compressed=1`, the `binemit` tests should check the smallest legal encoding whose register constraints is still satisfied.

**Comment by stoklund** [comment]
Fixed in 60431b31d11c8d6bf1d148b05925c178db5a1530 by @angusholder
