### ISSUE TITLE
test-all.sh exits early because of minor errors from flake8

### ISSUE THREAD

**Issue by pgarland** [stoklund/cretonne#134]
For me, running test-all.sh after running "cargo clean" currently halts after running the flake8 tests:

pgarland@rimbaud:~/Hacking/cretonne$ ./test-all.sh 
======  Rust formatting  ======
======  Python 2.7.13, Python 3.5.4rc1  ======
   === flake8 ===
./gen_legalizer.py:22:62: E261 at least two spaces before inline comment
./gen_legalizer.py:26:37: E261 at least two spaces before inline comment
./gen_legalizer.py:27:39: E261 at least two spaces before inline comment
./test_gen_legalizer.py:7:73: E261 at least two spaces before inline comment
./test_gen_legalizer.py:8:41: E261 at least two spaces before inline comment
./test_gen_legalizer.py:9:34: E261 at least two spaces before inline comment
./test_gen_legalizer.py:11:30: E261 at least two spaces before inline comment
./test_gen_legalizer.py:12:34: E261 at least two spaces before inline comment
./test_gen_legalizer.py:13:57: E261 at least two spaces before inline comment
./test_gen_legalizer.py:18:62: E261 at least two spaces before inline comment
./semantics/__init__.py:5:41: E261 at least two spaces before inline comment
./semantics/__init__.py:6:29: E261 at least two spaces before inline comment
./semantics/__init__.py:7:38: E261 at least two spaces before inline comment
./semantics/__init__.py:8:34: E261 at least two spaces before inline comment
./semantics/__init__.py:9:68: E261 at least two spaces before inline comment
./semantics/elaborate.py:11:68: E261 at least two spaces before inline comment
./semantics/elaborate.py:12:33: E261 at least two spaces before inline comment
./semantics/elaborate.py:13:37: E261 at least two spaces before inline comment
./semantics/elaborate.py:14:34: E261 at least two spaces before inline comment
./semantics/primitives.py:13:20: E261 at least two spaces before inline comment
./semantics/smtlib.py:15:56: E261 at least two spaces before inline comment
./semantics/smtlib.py:16:38: E261 at least two spaces before inline comment
./semantics/smtlib.py:17:32: E261 at least two spaces before inline comment
./semantics/smtlib.py:18:34: E261 at least two spaces before inline comment
./semantics/smtlib.py:20:42: E261 at least two spaces before inline comment
./cdsl/ast.py:14:37: E261 at least two spaces before inline comment
./cdsl/instructions.py:10:28: E261 at least two spaces before inline comment
./cdsl/isa.py:352:25: W503 line break before binary operator
./cdsl/isa.py:353:25: W503 line break before binary operator
./cdsl/test_ti.py:16:70: E261 at least two spaces before inline comment
./cdsl/test_ti.py:17:62: E261 at least two spaces before inline comment
./cdsl/ti.py:10:72: E261 at least two spaces before inline comment
./cdsl/ti.py:11:64: E261 at least two spaces before inline comment
./cdsl/ti.py:13:34: E261 at least two spaces before inline comment
./cdsl/ti.py:14:26: E261 at least two spaces before inline comment
./cdsl/ti.py:15:33: E261 at least two spaces before inline comment
./cdsl/types.py:6:55: E261 at least two spaces before inline comment
./cdsl/typevar.py:13:71: E261 at least two spaces before inline comment
./cdsl/xform.py:11:37: E261 at least two spaces before inline comment

While these should possibly be fixed, they don't seem a good reason to halt the test suite. 

The possible fixes that  jump to my mind are:
* don't use set -e in either test-all.sh or check.sh
* pass the --exit-zero flag to flake8 so that it always exits with a code of 0
* use the --ignore= or --select= flags to flake8 to explicitly specify which errors to check

I'm not a bash expert, so I may be missing other/better fixes. Of the 3 above possible fixes, passing --exit-zero to flake8 seems best as it shows the problems that flake8 discovers, but allows the rest of the tests to continue to run.

**Comment by stoklund** [comment]
The tests are passing on Travis CI. Do you have an old version of flake8 installed or a local configuration file?

**Comment by pgarland** [comment]
Updated my flake8 and test-all.sh now works correctly. I'm closing the issue.

Thanks for your help!
