### ISSUE TITLE
Add instruction labels to function printing

### ISSUE THREAD

**Issue by denismerigoux** [stoklund/cretonne#139]
When debugging using the verifier, you often have errors of the type `inst589: use of non-dominating arg value`. However it is impossible to locate `inst589` when printing the function later because the instruction labels are not printed.

It would be very valuable to print these when printing the function to be able to actually use the verifier error messages.

**Comment by denismerigoux** [comment]
You have the `DataFlowGraph::display_inst()` method that displays the instruction but when it displays something like this `inst589: trap` it doesn't really help locating the instruction in the code.

**Comment by stoklund** [comment]
I think that adding instruction numbers to every line of the text IL format would be too noisy. See #68 for a preferred solution.

**Comment by sunfishcode** [comment]
Closing this in favor of #68. Feel free to re-open or file a new issue if there's more to consider here.
