### ISSUE TITLE
Update to rustfmt 0.9.0?

### ISSUE THREAD

**Issue by sunfishcode** [stoklund/cretonne#149]
It's rarely a great time to change rustfmt versions, but 0.9 may be a local maximum. [This blog post](https://www.ncameron.org/blog/rustfmt-changes/) says 0.9 is likely to be the last stable update for the foreseeable future. And, 0.9 switched to the new RFC style in general, so while it obviously doesn't have everything that nightly rustfmt has, it's much closer than previous versions.

This bubbled up for me because I was working on other projects which happen to use 0.9 -- it's the current stable version -- and it's a minor hassle to switch rustfmt versions back and forth when moving between projects.

I'm willing to do the work, but I wanted to collect input here first.

**Comment by stoklund** [comment]
I'm ok with making this change.

I used to update rustfmt regularly, but stopped when they moved development to the nightly branch. It was always my intention to pick it up again when the new version was more stable.

Now is a good time, I don't think there are any big outstanding branches we need to worry about.

**Comment by stoklund** [comment]
BTW, this should be fairly simple to do:

1. Edit `VERS` in `check-rustfmt.sh`.
2. `./check-rustfmt.sh --install`
3. `./format-all.sh`
4. `git commit -a`

**Comment by sunfishcode** [comment]
And it's now done. I also had to also edit a few places to break some long lines up.

Glancing through the changes, one change that pops out is changes from

```
  moderately_long_function_name(lots,
                                of,
                                args)
```

to

```
  moderately_long_function_name(
      lots,
      of,
      args
  )
```

which is nice.
