### ISSUE TITLE
Support for symbolic memory addresses

### ISSUE THREAD

**Issue by sunfishcode** [stoklund/cretonne#182]
Cretonne doesn't seem to have a way to support global variables, in a C/C++/Rust sense. It has "globals", but they have to be defined in the VMCtx, or accessible from pointers in the VMCtx. There's no equivalent of `FunctionName` for globals, for example, which could be used for arbitrary addresses to be resolved by a subsequent link step.

Would it make sense to add a field to `GlobalVarData` holding a `FunctionName` (or whatever that may evolve into)?

**Comment by stoklund** [comment]
Yes, I think we should add a whole new variant to the enum.

**Comment by sunfishcode** [comment]
This PR doesn't yet add legalization support. I took a look at adding legalization support, however I encountered some difficulty.

`global_addr` with `VMCtx` or `Deref` globals needs to get legalized in one way, while eg. Intel needs to legalize `Sym` another way. This seemed like a task for instruction predicates, however it appears they only get passed the `InstructionData` contents, so they get the `GlobalVar` but not the `Function` to retrieve the `GlobalVarData` from.

I'm tempted to add a new opcode, like `globalsym_addr`, rather than overloading `global_addr`. What do you think?

**Comment by stoklund** [comment]
I though you might hit that problem. The `global_addr` instruction gets a little too abstract.

I think it would make sense to legalize `global_addr` into a more concrete opcode that materializes the address of an external symbol. You may want to consider if it makes sense to merge it with `func_addr`, but the two will probably want to reference their symbol differently.
