### ISSUE TITLE
Clarify `ExternalName` binary emit usage

### ISSUE THREAD

**Issue by m4b** [stoklund/cretonne#185]
So it looks like `ExternalName` is used in binemit and other places.  E.g., `wasmstandalone` uses it in function name emission:

https://github.com/sunfishcode/wasmstandalone/blob/04660ae8cc419cc9becdc675788c5393b78f872b/lib/runtime/src/lib.rs#L36 

The problem with this is that the symbol name is typically prefixed with a `%`; this is fine for internal usage, but for binaries, this will be very problematic for tools like gdb which won't allow disassembly of a function with a % prefixed, e.g.:

```
(gdb) disass 0x0
Dump of assembler code for function %wasm_0x0:
   0x0000000000000000 <+0>:	rex mov $0x0,%eax
   0x0000000000000006 <+6>:	rex mov $0x0,%eax
   0x000000000000000c <+12>:	callq  0x11 <%wasm_0x0+17>
   0x0000000000000011 <+17>:	retq   
End of assembler dump.
(gdb) disass %wasm_0x0
A syntax error in expression, near `%wasm_0x0'.
(gdb) disass \%wasm_0x0
Invalid character '\' in expression.
```

Should another function be used in this case, or should the client take care to emit different function names?

**Comment by sunfishcode** [comment]
The '%' prefix is added by `fmt`/`to_string`/etc. when printing, which is meant for Cretonne's text format. If you want the raw bytes, there's an `as_ref()` which returns a `&[u8]`.

**Comment by m4b** [comment]
Hmm. So specifically, for, e.g. `filetests/call.wat`:

```
(module
  (func $main (local i32)
    (set_local 0 (i32.const 0))
    (drop (call $inc))
  )
  (func $inc (result i32)
    (i32.const 1)
  )
  (start $main)
)
```

I was hoping to see `$main` and `$inc`

How hard would that be to return for the function name in current wasmstandalone?

**Comment by sunfishcode** [comment]
In wasm, function names aren't semantically meaningful, which is why I haven't wired them up yet. The names we'd really want would be the export names, such as if you added `(export "public_name_for_inc" (func $inc))`. It wouldn't be complicated to take the names from the exports and use them for function symbols.

**Comment by sunfishcode** [comment]
Also, I just realized that the '%' names were coming from wasm2obj, so I've now pushed a patch to fix that.

**Comment by m4b** [comment]
Ok I think its safe to close this, since iiuc:

1. export names (if specified in wasm file) are the external names wasm2obj needs to omit
2. otherwise names/functions are local (still would be nice to use the local name for debugging, etc.)
2. the % was minor bug in wasm2obj and is fixed now
