### ISSUE TITLE
Pager problems

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#196]
In 0538615ccc0b600d4f534dae2ee966d5ed0df9b7, pager functionality was added to the cton-util executable that runs the file tests. It's causing me some trouble:

- Every time I run `./test-all.sh` with no failures, I have to hit `q` to exit the pager and get back to the command line. This happens even when the cton-util output is less than a screenfull.
- If I run `PAGER=less LESS="--quit-if-one-screen" ./test-all.sh`, less does quit right away, but the single screenfull of text is not visible on the terminal afterwards.
- The pager doesn't work as intended, I think. When there *is* a test failure, the error message is dumped on stderr, but the pager only captures stdout which has the list of slow tests.

Could we remove this pager functionality again, or at least make it optional?

I think it would make sense to take another look at how we compute "slow" tests if that list is the problem. The tests that are listed as slow now are not actually problematic.

cc @sunfishcode

**Comment by sunfishcode** [comment]
I'm ok removing it.
