### ISSUE TITLE
Dominator tree

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#2]
Cretonne's in-memory IR needs a dominator tree analysis for verification, and likely for register allocation.

We expect most input programs to have structured control flow, so the [Cooper / Harvey / Kennedy algorithm](http://www.cs.rice.edu/~keith/EMBED/dom.pdf) will work well.

- Should the dominator tree be a static analysis, or should it be dynamically updated when the CFG (#1) changes?
- How does a dominator tree interact with EBBs? The immediate dominator of every inner basic block in an EBB is obvious (it's the previous basic block), so it doesn't need to be stored. Inly the immediate dominator of an EBB is interesting.

**Comment by mrrrgn** [comment]
A rough draft: https://github.com/mrrrgn/cretonne/commit/f6dd0270d0f8f09e82c7a6be74548cd6ec69f15f

**Comment by mrrrgn** [comment]
Closing this for now. https://github.com/stoklund/cretonne/blob/master/src/libcretonne/dominator_tree.rs
