### ISSUE TITLE
Document NaN propagation semantics

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#20]
The language reference is not so clear on what happens when floating point arithmetic instructions produce a NaN. We should specify that.

- Can instructions return a signaling NaN or only quiet NaNs?
- When propagating a NaN input, can the payload bits change?

The specification should be tight enough that WebAssembly semantics are simple to represent, and loose enough that we don't need lots of NaN adjustment code emitted for `fadd` on common targets.

Copying the WebAssembly semantics is probably a good choice.

**Comment by serprex** [comment]
For reference: https://github.com/WebAssembly/design/pull/660

**Comment by sunfishcode** [comment]
Some background questions:

 - Can Cretonne depend on the IEEE 754-2008-recommended encoding for signaling NaN? This would simplify some things in the NaN rules, with the only practical downside being incompatibility with older (though still in use) MIPS CPUs. For reference, [WebAssembly has this dependency](https://github.com/WebAssembly/design/issues/976), though Rust doesn't.

 - Should Cretonne keep the non-associative `minnum`/`maxnum` operators?
     - On one hand, these map to instructions on ARM and Power.
     - On the other, they need special-casing in the NaN rules, IEEE 754-2018 is expected to remove them, WebAssembly omitted them, and [Rust doesn't depend on their particular sNaN behavior](https://github.com/rust-lang/rust/pull/42430).

**Comment by stoklund** [comment]
- I think we should follow WebAssembly on NaN representations for now. We can revisit if old MIPS chips become relevant for us.
- I would be OK with removing `fmaxnum` and `fminnum`. We should add a note to the remaining `fmin` and `fmax` to make it clear that they are not the functions from IEEE 754-2008.
