### ISSUE TITLE
Install `wat2wasm` on CI so that wasm tests run

### ISSUE THREAD

**Issue by pchickey** [stoklund/cretonne#200]
Building and installing wabt requires cmake and a c++ compiler. Two ways to do this, with a tradeoff on how many deps a `test-all.sh` implies:

* I can add an installation step to the `.travis.yml`, so it runs in CI. This is easy enough.
* I can add wabt as a submodule, and add a build.rs to lib/wasm that builds it, like in https://github.com/paritytech/parity-wasm/blob/master/spec/build.rs. That adds cmake, c++ compiler, and the cmake crate as a dep to everyone's build, but it ensures that it does get tested by every `test-all.sh`.

**Comment by stoklund** [comment]
I think it’s best to keep the Travis CI cycle times low, so I would prefer to install a binary dependency.

We can add a note to README.rst about installing wabt locally

**Comment by pchickey** [comment]
I think the easiest place to get a binary package is from the https://wasm-stat.us buildbot. Here is the url of the last good build's package, its 98M: https://storage.googleapis.com/wasm-llvm/builds/linux/26619/wasm-toolchain_0.1.26619_amd64.deb

We could pin to that build, or we could do something more sophisticated to query the buildbot api to find the last known good build and fill in that version number? I think pinning to that build until there's a reason to update is probably fine.

**Comment by stoklund** [comment]
Yeah, I agree

**Comment by pchickey** [comment]
Closed by #202
