### ISSUE TITLE
Cretonne compile stage value interference

### ISSUE THREAD

**Issue by pchickey** [stoklund/cretonne#207]
@tyler and I discovered what may be a Cretonne issue during the `compile` stage that we do not understand. There is a failure compiling the musl libc `strstr` function (unfortunately, it has rather nightmarish control flow). We compiled strstr to wasm with clang-5.0.0 wasm32-unknown-unknown, and then ran that through our wasm Cretonne driver (the equivalent driver in `cton-util wasm` seems to panic before getting to codegen, I didn't investigate why yet). We grabbed the cretonne IL out of cretonne.dbg.main and converted it into a filetest for reproduction. We get the following error: `FAIL ../cton-sbx/tests/strstr.cton: compile(u0:3): v625: Value def in vreg34 interferes with v619`. 

Both the source wasm and the IL are here: https://gist.github.com/pchickey/cf4d6bb852c4155ad785e320eb8ea6ad

When we excluded strstr from our build to get it to go further, we have seen this same sort of error message in subsequent files. If I can manage to narrow the test case at all, I will post another gist.

**Comment by pchickey** [comment]
Added another pair of files to that gist for `vfprintf`, which produces a similar error. vfprintf has got probably the gnarliest control flow out of everything we build in musl, so its probably even harder to go through.

**Comment by stoklund** [comment]
Thanks.

I've made a fundamental error in the design of the CSSA coalescer. I have other test cases that fail the same way in functions with gnarly control flow.

I know how to fix it, and it is my project for this week.
