### ISSUE TITLE
Verifier error where two values "must be in same register"

### ISSUE THREAD

**Issue by pchickey** [stoklund/cretonne#208]
We hit these errors in the same was as #207, but the error is different. Got 15 different occurrences in the ~300 files we compile in musl, fortunately many of them were for some rather small wat files.
 
Here's one for strtok_r:
https://gist.github.com/pchickey/a1e69baee24eeaa148fc1312e3da0bdc
Here's one for __stdio_exit:
https://gist.github.com/pchickey/4ec66fb88065306d9ea3784f0595ac42

**Comment by stoklund** [comment]
Thanks. This could be the same problem as #207, or it could be something else. I'll look into it.
