### ISSUE TITLE
Intel mov encoding bug

### ISSUE THREAD

**Issue by pchickey** [stoklund/cretonne#211]
We discovered an intel encoding bug for mov.

We found a cretonne instruction that is load.i64 with destination register r13.
morally trying to do `mov (%r13),%r13`. Cretonne uses the `ld` recipe because
the displacement is 0. It chooses the encoding `4d 8b 2d`.

Those bytes actually encode a rip-relative addressed load with a 32-bit
displacement. the ModRM byte has a special case where it acts as a rip-relative
load iff in_reg0's bottom 3 bits == 5.

This means that when cretonne uses register 5 (which never happens because thats %rbp) or 13 (which does when you have enough register pressure) with this recipe, the code
it outputs will be incorrect. We tried to figure out a way to exclude those
registers but couldn't figure out a way to specify a RegClass of non-contigious
registers, and we couldn't find a way to add a predicate that ensures those
registers will not be used.

The correct encoding in this case is to use a ModRM byte that also expects a
disp8 afterwards, which will allow you to use register 13 as the destination.
The disp8 is just 0. We confirmed this encoding using gcc as `4d 8b 6d 00`.

We aren't sure if this issue effects other instruction encodings.

We hit the bug running musl's memcpy implementation, compiled through clang 5.0 wasm32-unknown-unknown and s2wasm. Because that code does uintptr fiddling to try to optimize for aligned loads and stores, is a very bad implementation for wasm, but it is interesting because it creates lots of register pressure, and helped us find this cool bug :) . cton file is uploaded here: https://gist.github.com/pchickey/79dd8f9a87c859233b97145de7b77703

**Comment by tyler** [comment]
@stoklund: We're more than happy to do the work to fix this. We just need some advice on what direction to take in fixing it.

**Comment by stoklund** [comment]
Sorry for missing this, it must have gotten buried in the holiday business.

I didn't know there was a special case for `%r13` too, I thought it was only `%rbp` that had this exception. You are right, of course.

I think the right way of fixing this is to use a RegClass constraint on the encoding that excludes `%rbp` and `%r13`. On the Rust side of things, register classes are already represented as bit masks of units (see `isa::RegClassData`), but you are right that we don't have any Python syntax for expressing non-contiguous register classes.

In the Python code, the `cdsl.RegClass` class does not use a bit mask to represent its registers. I don't think it is too hard to change to a bit mask representation using Python's long integers for example. You should also change the `RCTup` type to be `Tuple[int, long]` where the first number is the class's register width and the second number is the bit mask of units.

This type of register class is rare enough that we don't need to be too fancy with the Python syntax to create them. I think something like this would do:

```python
GPR_NORIP = GPR.without(GPR.rbp, GPR.r13)
```

**Comment by stoklund** [comment]
Is this fixed now?

**Comment by tyler** [comment]
It appears to fixed now, yes. Thank you!
