### ISSUE TITLE
"inst9: uses value arg from non-dominating ebb0"

### ISSUE THREAD

**Issue by kripken** [stoklund/cretonne#214]
Found&reduced by the binaryen fuzzer. STR:
```
target/release/cton-util wasm --set=is_64bit '--isa=intel haswell' ww.wasm
```
[ww.zip](https://github.com/stoklund/cretonne/files/1616256/ww.zip)
```
(module
 (type $0 (func (result i32)))
 (type $1 (func))
 (global $global$0 (mut i32) (i32.const 10))
 (table 1 anyfunc)
 (memory $0 1 1)
 (func $0 (; 0 ;) (type $0) (result i32)
  (if (result i32)
   (i32.const 0)
   (i32.const 0)
   (block (result i32)
    (if
     (loop $label$3 (result i32)
      (unreachable)
     )
     (drop
      (loop $label$5 (result f32)
       (set_global $global$0
        (i32.const 1)
       )
       (f32.const -nan:0x7f880e)
      )
     )
    )
    (i32.const 1)
   )
  )
 )
)
```

**Comment by stoklund** [comment]
Thanks! Is this fixed by the verifier patch I just pushed? It looks like it is the same issue from the error message.

**Comment by kripken** [comment]
Confirmed fixed by the recent master changes.

**Comment by jfoote** [comment]
Hello @kripken o/ I'm planning to fuzz a Cretonne-based toolchain and was wondering: were you feeding testcases from [binaryen/wasm-opt](https://github.com/WebAssembly/binaryen/wiki/Fuzzing) (generated more-or-less standalone) into Cretonne (`cton-util wasm`), or were you doing something else?

I'd be happy to chat via some more appropriate medium if you'd like, just let me know. Thanks regardless!

**Comment by kripken** [comment]
Happy to help @jfoote !

I did a bunch of things:

 * run binaryen's wasm-opt with -ttf (translate-to-fuzz, so it translates the input from random bytes into a valid wasm file; that lets it be driven by say afl-fuzz), and see if cton-util crashes on that.
 * do the same but use the spidermonkey integration of cton-util to be able to run the js+wasm combination that wasm-opt emits. that checks for incorrectness (e.g. I see what is printed with cretonne turned on vs off; the js will print the output of each wasm function as it is executed).
 * run the spidermonkey+cretonne on the emscripten test suite. Not fuzzing, but it covers a wide array of C/C++ code.

**Comment by jfoote** [comment]
Excellent, thank you @kripken !
