### ISSUE TITLE
fuzz bug "[..] is a ghost value"

### ISSUE THREAD

**Issue by kripken** [stoklund/cretonne#215]
(from binaryen fuzzer).

STR: `../cretonne/target/release/cton-util wasm --set=is_64bit '--isa=intel haswell' w.wasm`

[w.zip](https://github.com/stoklund/cretonne/files/1616335/w.zip)

**Comment by stoklund** [comment]
This looks like a problem with the register coalescer. It's a bit more complicated to fix.

**Comment by kripken** [comment]
Btw, what's a "ghost value"?

**Comment by stoklund** [comment]
Ghost values represent values that have been "optimized out", so they can't be found in a register or stack slot any longer. They will eventually be used to generate DWARF for debugging, or some form of recovery instructions for de-optimization.

**Comment by kripken** [comment]
I see, thanks!
