### ISSUE TITLE
fuzz bug: "Ran out of registers in GPR"

### ISSUE THREAD

**Issue by kripken** [stoklund/cretonne#227]
[ww.zip](https://github.com/stoklund/cretonne/files/1644433/ww.zip)

This is on latest master.

**Comment by kripken** [comment]
Using a very different fuzzing approach, I got this other testcase. It's larger, but maybe it's easier to debug.
[www.zip](https://github.com/stoklund/cretonne/files/1644562/www.zip)

**Comment by kripken** [comment]
I also see that this occurs on real-world code, on zlib.

**Comment by stoklund** [comment]
Thanks!

This one also has the mystery reproducibility issues that I found in #219, but I think I've found the cause. The coloring pass has a solver that sorts its variables, using the value number as the last-resort tie breaker. The failing case has:

```
v13(GPR d=1, out, global, def, 1), 
v4(GPR d=4, from %r8, in, out, 4), 
v5(GPR, from %r14, in, out, 4), 
v12(GPR, from %rax, in, 4), 
v15(GPR, from %r15, in, out, 4)
```

While the attempt to reproduce gets new value numbers and swaps the last two variables:

```
v21(GPR, out, global, def, 1), 
v4(GPR, from %r8, in, out, 4), 
v5(GPR, from %r14, in, out, 4), 
v7(GPR, from %r15, in, out, 4), 
v20(GPR, from %rax, in, 4)]
```

With the first variable order, the solver fails to find a solution, even though one exists.
