### ISSUE TITLE
Parse value aliases

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#23]
The `write_value_aliases()` function will print out any value aliases used by an instruction on lines before the instruction itself:

```
vx3 -> v4
v1 = iadd_imm vx3, 17
```

The parser in `lib/reader` should be taught to handle these aliases.

Since the parser is used mostly for test cases, value aliases in the input should be translated to value aliases in the in-memory IR. We don't want to resolve aliases in the parser, even though that would be easy.

- Create value aliases as they are encountered in the source.
- The same alias may appear multiple times. Verify that the instances are consistent.
- A value alias may be created before the source value has been defined, so all of the aliases need to be rewritten, just like other value and EBB references.

**Comment by KiChjang** [comment]
Hi there! I'm currently taking a look at this issue, and I'm sort of confused when you say "the parser in `lib/reader` should be taught to handle these aliases", only to immediately say "we don't want to resolve aliases in the parser". Where should the handling of these aliases occur?

**Comment by stoklund** [comment]
Hi! Thanks for working on this.

Let me try to clarify: The parser should be able to understand the syntax `vx3 -> v4` in the example above, and it should create a value alias to represent `vx3`. By *resolving aliases*, I mean replacing any uses of `vx3` with `v4`. That would also be possible for the parser to do since it already has a value rewriting pass. It would generate this code:

```
v1 = iadd_imm v4, 17
```

after parsing the example above. That is *not* what we want. Instead, we want the parser to create a new value alias so the parsed function would be printed like this:

```
vx3 -> v4
v1 = iadd_imm vx3, 17
```

Note that currently, the only way of creating a value alias is the `change_to_alias()` method. You will probably need to add a `make_value_alias()` method to the `DataFlowGraph` type.

**Comment by KiChjang** [comment]
So here's a bit of complexity that I'm running into... `parse_instruction` and the soon-to-be-called `parse_value_alias` will run into parser ambiguity because both statements can start with a Value token. I am thinking of extracting the logic for parsing the first Value out of `parse_instruction` and put it in `parse_extended_basic_block`, but it's not as simple as that since `parse_instruction` also handles comments as well. Should that also be moved to `parse_extended_basic_block`?

**Comment by stoklund** [comment]
If it's simpler that way, I think it would be OK to make the grammar LL(1) by introducing an `alias` keyword:

```
alias vx3 -> v4
v1 = iadd_imm vx3, 17
```

But otherwise, your suggestion of parsing the list of result values in `parse_extended_basic_block` sounds good to me. I think I would prefer to avoid introducing keywords that can conflict with the instruction opcode namespace.

The call to `gather_comments(NO_INST)` is there to make sure that a comment on the same line as the instruction gets associated with that instruction, and not the previous one. I think it is OK to do that call in `parse_extended_basic_block`.

**Comment by stoklund** [comment]
Moving the `gather_comments` call would affect code like this:

```
v1 = iadd_imm vx3, 17
v2 ; comment now associated with iadd_imm
   = imul v13, v14
```

I don't think that is a problem at all. I imagine that newlines will be banned from inside instructions at some point in order to avoid ambiguities like:

```
return v1
```

 vs

```
return
v1 = iadd_imm  vx3, 17
```

Right now, we only avoid that ambiguity because `return` is a terminator that must be the last instruction in an EBB. That's a little too lucky.

**Comment by KiChjang** [comment]
I also missed something on my previous comment -- the other idea I had was to simply make it so that a value alias is an instruction itself (i.e. process the value alias within `parse_instruction`). I didn't feel like that this is a good solution because I would not categorically put aliasing as an instruction, but maybe you have different thoughts about this.

**Comment by stoklund** [comment]
Well, that would have some symmetry with the writer, where `write_instruction` calls `write_value_aliases`.

As I said, I expect that newlines will become significant in the text format, so instructions are always separated by newlines. In that case, aliases and instructions would also go on separate lines.

I think all of these solutions are acceptable, but I am leaning to your first suggestion of parsing the initial result list before calling `parse_instruction`.

**Comment by KiChjang** [comment]
Alright, I'm going to implement my first option, but that gives rise to another issue: do we want to support multi-variable aliasing in one statement? i.e. the following syntax:
```
vx3, vx4 -> v14, v15
```

**Comment by stoklund** [comment]
No, I don't think we need to support that syntax. It would be printed as

```
vx3 -> v14
vx4 -> v15
```

instead.
