### ISSUE TITLE
Generic representation of isa-specific flags

### ISSUE THREAD

**Issue by pchickey** [stoklund/cretonne#233]
I am trying to debug an issue and wanted to rule out the isa-specific flags given by cretonne-native's cpuid detection as a variable.

Currently the `TargetIsa` trait has no way to show the user anything about the private, isa-specific `isa_flags` member that exists in all the per-isa `Isa` structs. The flags for each of those have a helpful `Display` impl but I couldn't figure out any way to get at even that string repr without exposing another method in `TargetIsa`.

One idea I had was to make `TargetIsa` imply `Display`, so that there is an easy way to get the display of both the shared flags and the isa-specific flags out of the trait object. I could also just add another method that gives a string, or takes a formatter, to display just the isa-specific flags. Which, if any, of those would you prefer to see?

**Comment by stoklund** [comment]
I could have sworn I had something like this already, but I can't find it. I think it's a great idea to have `TargetIsa` imply `Display` so you can just print it.
