### ISSUE TITLE
Measure generated code size

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#244]
Add a command-line option to `cton-util wasm` for measuring the generated code size. The code size of a function is the number returned by `Context::compile()`.

When compiling a wasm module, it is useful to be able to report:

1. Per-function wasm bytecode size and machine code size.
2. Aggregate sizes (bytecode and machine code) for the whole module.

While we still have a lot of low-hanging fruit in the generated code quality, code size is a good proxy for performance, and it is much easier to measure.

**Comment by bnjbvr** [comment]
Trying this.
