### ISSUE TITLE
General type inference and type checking for transformation patterns

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#25]
In `legalize.py` and other places, we define *transformation patterns* like this:

```python
# Expansions for immediates that are too large.
expand.legalize(
        a << iadd_imm(x, y),
        Rtl(
            a1 << iconst(y),
            a << iadd(x, a1)
        ))
```

Each transformation pattern is represented by the `XForm` class defined in `meta/cdsl/xform.py`.

We need a general type inference and type checking system for these patterns that uses the type constraints specified through type variables in the instruction definitions. The type inference is used to:

- Infer the types of temporary symbols such as `a1` in the output pattern above. The generated transformation code can't always depend on the simple forward type inference that many `InstBuilder` methods support.
- Detect cases where the types of temporary symbols in the output can't be inferred from the types available in the input pattern and issue an error.
- Verify ahead of time that the type constraints make sense, and we won't generate code that doesn't verify.
- Inform the generation of test cases for an SMT solver. At some point we want to use z3 or another SMT solver to verify each transformation pattern. Since SMT solvers don't accept polymorphic problems, we need to select valid types for the symbols used in a pattern, or possible enumerate all valid type combinations to generate test cases.
- Detect cases where a transformation only applies to a subset of the types that the input pattern can represent. This leads to additional preconditions to be checked before applying a pattern.

We currently have a type inference implementation that:

- Assigns a type variable to every symbol used in the pattern. These variable can be free or derived from other type variables.
- Collects a list of free type variables.
- Complains of any of the free type variables are associated with a temporary symbol which only appears in the output.

The current implementation does not compute strict type sets for each type variable, and it is not clear that it can always determine a way of computing the type of a temporary symbol.

### Free type variables

A general implementation of the type inference should first compute a set of free type variables, such that the type of every symbol can be computed as a function of these variables.

The type constraints imposed by the instructions in the pattern can be represented as a set of triples:

```
(Var, Func, Var)
```

Here, `Var` is a symbol in the pattern, and `Func` is one of the type variable functions listed in the `TypeVar` class. The meaning of a tuple `(a, f, b)` is the constraint that `typeof(a).f() == typeof(b)`. The function can be `TypeVar.SAMEAS` to require `a` and `b` to be of the same type.

The set of tuples can also be seen as a labeled, directional graph where the nodes are symbols and the labeled edges are constraints. We need to prove that every temporary symbol (i.e., one that appears only in the output pattern) can be reached from a symbol that appears in the input pattern.

Determine a root set of free variables such that the entire graph can be reached for that root set. The set doesn't have to be minimal, but smaller is better.

If the root set can consist of mutually independent type variables, even better. This would make it much easier to enumerate all the possible type combinations for an SMT solver.

### Type sets

In the instruction definitions, every type variable has an associated set of allowed types. We should compute the corresponding type sets for the free pattern type variables.

The current implementation is incomplete. It doesn't do anything with type variable functions.

**Comment by stoklund** [comment]
@d1m0, is this complete now?

**Comment by d1m0** [comment]
This is all done except for: 

- Detect cases where a transformation only applies to a subset of the types that the input pattern can represent. This leads to additional preconditions to be checked before applying a pattern.

I think PR #112 addresses this, but you should confirm that.

**Comment by d1m0** [comment]
With the merge of #112 I think this can be closed.
