### ISSUE TITLE
Memory pool and B-tree representation for live ranges

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#38]
The `LiveRange` struct currently uses a `Vec<Interval>` to store its list of live-in intervals. This has some problems:

- The vector is often empty, but it still has a 24-byte footprint.
- The vector causes fine-grained heap allocation which is slow.
- In degenerate cases, computing a live range can take quadratic time because new live-in intervals are being inserted near the front of a large vector. (Note that LLVM's `LiveInterval` has the same weakness, and it hasn't yet caused known compile time issues.)

These problems can be fixed in a way similar to #35, but instead of allocating lists from a memory pool, we allocate B+-tree nodes. This is similar to representing the live-intervals in a `BTreeMap<Ebb, Inst>`. Unfortunately, Rust's standard B-tree is not useful to us since it allocates nodes from the heap, and it doesn't provide a rich enough interface to allow things like coalescing intervals, see #37.

# Implementation

- The node pool is implemented with a vector of tree nodes.
- Nodes are identified by 32-bit references that are simply indexes into the vector.
- Nodes are cache line sized (64 bytes).
- The `LiveRange::liveins` vector becomes a 32-bit node reference with a sentinel value to indicate 'empty'.

The B-tree node is defined as an enum:

```rust
enum Node {
    Inner {
        size: u8,
        keys: [K; 7],
        nodes: [NodeRef; 8],
    }
    Leaf {
        size: u8,
        keys: [K; 7],
        values: [V; 7],
    }
}
```

**Comment by dcci** [comment]
I'd like to work on this one because I find it interesting, if you're fine with it. Do you think it's reasonable as first step starting with a B-tree implementation? Do you have any recommendations about the interface?

**Comment by stoklund** [comment]
That sounds great! I agree you should start with a generic B+-tree implementation.

I have some ideas about the implementation. I think it is important we don't build a clone of the excellent `BTreeMap` that Rust already has. We can make some assumptions:

- Expect both keys and values to be 32-bit entities. This doesn't have to be a hard requirement, but it's OK to use a fixed node layout as I did above and expect it to fit in a cache line.
- Keys and values can be required to implement both `Copy` and `Default`. This means you don't need to mess around with unsafe code in order to implement uninitialized elements in the nodes.

Take a look at `entity_list.rs` for inspiration to the interface. Most operations on a B-tree will require a reference to the corresponding node pool, just like most `EntityList` methods take a `ListPool` reference.

- A B-tree data structure should only be 32 bits large, containing only the root node number. This is like `EntityList`.
- There should be a node pool data structure containing a `Vec<Node>`. The pool can be shared by many B-trees, just like a `ValuePool`. Give it a simple free list to keep track of unused nodes.
- It's OK if the node pool is `<K,V>` generic. I prefer the simplicity of avoiding unsafe code for now.

We need a different interface than `BTreeMap` for searching and modifying a B-tree. Take a look at the `LiveRange::extend_in_ebb()` method. This algorithm does a binary search to find the right insertion spot, then does one of the following:

- Merge the new interval with the interval before the insertion spot.
- Merge the new interval with the interval after the insertion spot.
- Marge all three into one interval.
- Insert a new interval.

I would like to be able to do this in only one binary search, like it is done in the current implementation. The `BTreeMap` interface can't do that. I think we need a kind of cursor that can point to a position in a B-tree and allow you to move around and modify both keys and values where the cursor is pointing. This is similar to both Cretonne's `layout::Cursor` and [LLVM's `IntervalMap`](http://llvm.org/docs/doxygen/html/IntervalMap_8h_source.html).

A B-tree cursor would need to contain an array of pointers to the whole path from the root to the current leaf node. The nodes themselves don't contain upwards or sibling pointers, so it is the only way you can navigate the tree. Note that since the branching factor in every node is at least 4, you can use a statically sized path with 16 levels. This means that a `Cursor` doesn't need to allocate heap memory either.

Don't hesitate to ask more questions or post code you'd like me to look at.

**Comment by dcci** [comment]
@stoklund 
Initial proposed interface. I preferred to start simple and get bare mininimum there (just a skeleton).
Once we agree on how this should look like, I can start implementing the functions.
https://gist.github.com/dcci/4f0a5ec191d864f3a2f2f67f22ef429b

**Comment by stoklund** [comment]
Thanks, @dcci. This is a good start. A few comments:

```rust
pub struct BTree<K, V> {
    index : u32,
    unused1: PhantomData<K>,
    unused2: PhantomData<V>
}
```

This is pretty much what I had in mind. Maybe use `NodeRef` instead of `u32`? We don't have to bikeshed type names now, but I do expect that we will have both set and map variants of this data structure. See #39.

```rust
/// An enum representing a B-tree node.
/// Keys and values are required to implement Copy and Default.
pub enum Node<K, V> {
```

Yep. After considering a bit, perhaps we don't need to require `Copy` for the value type? It's not critical, but see if you can get by without it. Requiring `Default` is definitely ok.

I don't think the `Node` type should be public. It's an implementation detail.

```rust
/// Memory pool for nodes.
pub struct NodePool<K, V> {
    // The array containing the nodes.
    data : Vec<Node<K, V>>,

    // A free list
    freelist : Vec<Node<K, V>>
}
```

Looks good. I think you mean `Vec<NodeRef>` for the free list.

```rust
/// Get a B-tree node.
pub fn get(&self, index: u32, pool: &NodePool<K, V>) -> Option<Node<K, V>> {
```

Should this be a method on the pool instead? It should probably return a reference. (`Option<&Node<K, V>>`).

I think it's convenient to implement `insert` and `remove` methods on the `BTree` (but don't expose the `Node` type). But I think your life will be easier if you implement a `Cursor` type first and then implement these two in terms of the cursor.

The cursor type works something like this:

```rust
impl BTree<K, V> {
    /// Search for `key` and return a `Cursor` that either points at `key` or the position where it would be inserted.
    pub fn search(&mut self, key: K) -> Cursor<K, V> {...}
}

struct Cursor {
    pool: &mut NodePool<K, V>,
    height: usize,
    path: [(NodeRef, u8); 16]
}

impl Cursor<K, V> {
     /// The key at the cursor position. Returns `None` when the cursor points off the end.
     pub fn key(&self) -> Option<K>;

     /// The value at the cursor position. Returns `None` when the cursor points off the end.
     pub fn value(&self) -> Option<&V>;

    /// Move to the next element.
    /// Returns `false` if that moves the cursor off the end.
    pub fn next(&mut self) -> bool;

    /// Move to the previous element.
    /// Returns `false` if this moves the cursor before the beginning.
    pub fn prev(&mut self) -> bool;

    /// Insert a `(key, value)` pair at the cursor position.
    /// It is an error to insert a key that would be out of order at this position.
    pub fn insert(&mut self, key: K, value: V);

    /// Remove the current element.
    pub fn remove(&mut self);
}
```

I imagine that a cursor can point at any pair in the map, and it can also point at a position before the first element and one after the last element. It's possible that we don't need both end points.

**Comment by dcci** [comment]
Take 2 (incorporating all your suggestions, fixing default visibility etc..)

```
use std::marker::PhantomData;

// A Node reference is a direct index to an element of the pool.
type NodeRef = u32;

/// A B-tree data structure which nodes are allocated from a pool. 
pub struct BTree<K, V> {
    index : NodeRef,
    unused1: PhantomData<K>,
    unused2: PhantomData<V>
}

/// An enum representing a B-tree node.
/// Keys and values are required to implement Default.
enum Node<K, V> {
    Inner {
        size: u8,
        keys: [K; 7],
        nodes: [NodeRef; 8],
    },
    Leaf {
        size: u8,
        keys: [K; 7],
        values: [V; 7],
    }
}

/// Memory pool for nodes.
struct NodePool<K, V> {
    // The array containing the nodes.
    data : Vec<Node<K, V>>,

    // A free list
    freelist : Vec<NodeRef>
}

impl<K: Default, V: Default> NodePool<K, V> {
    /// Create a new NodePool.
    pub fn new() -> NodePool<K, V> {
        NodePool {
            data : Vec::new(),
            freelist : Vec::new()
        }
    }
    
    /// Get a B-tree node.
    pub fn get(&self, index: u32) -> Option<&Node<K, V>> {
        unimplemented!()
    }

}

impl<K: Default, V: Default> BTree<K, V> {
    /// Search for `key` and return a `Cursor` that either points at `key` or the position where it would be inserted.
    pub fn search(&mut self, key: K) -> Cursor<K, V> {
        unimplemented!()
    }
}

pub struct Cursor<'a, K: 'a, V: 'a> {
    pool: &'a mut NodePool<K, V>,
    height: usize,
    path: [(NodeRef, u8); 16]
}

impl<'a, K: Default, V: Default> Cursor<'a, K, V> {
     /// The key at the cursor position. Returns `None` when the cursor points off the end.
     pub fn key(&self) -> Option<K> {
        unimplemented!()
     }

     /// The value at the cursor position. Returns `None` when the cursor points off the end.
     pub fn value(&self) -> Option<&V> {
         unimplemented!()
     }

    /// Move to the next element.
    /// Returns `false` if that moves the cursor off the end.
    pub fn next(&mut self) -> bool {
        unimplemented!()
    }

    /// Move to the previous element.
    /// Returns `false` if this moves the cursor before the beginning.
    pub fn prev(&mut self) -> bool {
        unimplemented!()
    }

    /// Insert a `(key, value)` pair at the cursor position.
    /// It is an error to insert a key that would be out of order at this position.
    pub fn insert(&mut self, key: K, value: V) {
        unimplemented!()
    }

    /// Remove the current element.
    pub fn remove(&mut self) {
        unimplemented!()
    }
}

fn main() {
    ()
}
```

You want me to start filling these methods or I can submit a pull req with the skeleton and we iterate from there incrementally?

**Comment by stoklund** [comment]
This looks like a good starting point to start filling out.

I don't mind reviewing and merging a PR with this skeleton if you prefer.
