### ISSUE TITLE
Is it possible to use cretonne to create a sandboxed plugin system?

### ISSUE THREAD

**Issue by hh9527** [stoklund/cretonne#41]
client code (rust) -> MIR -> wasm?
will generated binary code can call FFI functions (from hosted process, no link needed)?

**Comment by stoklund** [comment]
It possible, but non-trivial. It will be possible to call FFI functions.

Cretonne is only the code generator. It doesn't provide a sandbox or VM environment, and it doesn't help you figure out how to share memory between your sandbox and main application.
