### ISSUE TITLE
Write and parse ABI annotations on function signatures

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#49]
In c8be39fa9d06ccf7fb5765c125c16672cebce992 I added support for ABI annotations on function signatures. These annotations indicate the location (stack or register) of individual function arguments and return values. We need:

- Support for writing the ABI annotations using the correct ISA names for registers.
- Support for parsing the ABI annotations in test files with a single unique ISA. Related to #24.

# Writing ABI annotations

The new syntax for function signatures is partially implemented:

```
function average(i32 [%x10], i32 inreg [%x11]) -> f32 [%f10] {
```

If a signature has ABI annotations, they appear in brackets after each argument or return value. This is used everywhere function signatures appear:

- In the function definition.
- In a `signature` declaration in the preamble.
- In a `function` declaration in the preamble.

Each argument is annotated as follows:

- Registers: `[%x10]` using the `display_regunit()` function provided by the `TargetIsa`. Note that the currently committed implementation is incorrect, it just prints the register unit number `[%10]`. This is a stopgap until we can provide a `&TargetIsa` reference. It is not a syntax we want to support going forward.
- Stack arguments: `[24]`, where the number in brackets is the argument's byte offset in the argument array.
- Unassigned arguments don't get an annotation in the text format.

The `Signature` struct also has an `argument_bytes` field now which indicates the needed size of the argument array. This field does not need to appear in the text format since it can be computed from the arguments.

# Parsing ABI annotations

The parser should accept the annotations above and fill in the `location` field of the `ArgumentType` structs when present.

When parsing a file that doesn't specify exactly one ISA, the ABI annotations should be ignored.

After parsing a signature containing with ABI annotations, call the `Signature::compute_argument_bytes()` method.

**Comment by stoklund** [comment]
I've implemented the display part of this one, with a test case in `filetests/isa/riscv/abi.cton`. Maybe the remaining parser work is for @angusholder ?

**Comment by angusholder** [comment]
I'll get onto this now

**Comment by stoklund** [comment]
Fixed by @angusholder !
