### ISSUE TITLE
Only assume local type inference when writing text format IL

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#63]
Cretonne's IL parser supports a limited form of type inference for some polymorphic instructions where the controlling type variable can be inferred from one of the input operands:

```
    v0 = iconst.i32 2
    v1 = iconst.i8 6
    v2 = ishl v0, v1
```

The `ishl` instruction is polymorphic, but its `i32` result type can be inferred from the type of the `v0` operand.

The parser's type inference is best effort only, and in particular, it only knows the types of values that have been defined earlier in the input text. If `v0` were defined in an EBB later in the text format, we would have to use:

```
    v2 = ishl.i32 v0, v1
```

It would be technically possible for the parser to defer type resolution until everything has been parsed so that more missing types could be inferred. I don't think this is desirable, though. Cretonne IL is not a programming language, it is a language for writing unit tests, so obvious typing is better. It is also possible to write test cases in Cretonne IL that are somewhat malformed. For example, defines don't have to dominate uses, and it is useful to be able to write verifier test cases like that.

## Local type inference

The limited type inference is useful for reducing clutter, though. If a value is defined previously in the same EBB, its type is usually obvious, so there is no need repeat its type.

Currently, the instruction writer in `write.rs` is assuming a very smart type inference mechanism, even smarter than what the parser can do. It should be fixed to only depend on local type inference.

*Only omit the type variable when printing an instruction with a type variable operand that is defined in the same EBB.*

There is a TODO in the `type_suffix()` function.

**Comment by KiChjang** [comment]
Makes sense for me to look at this since I've just recently touched some of the type inference in the parser.

**Comment by stoklund** [comment]
Do it!

**Comment by KiChjang** [comment]
So I can use `func.dfg[inst].typevar_operand()` to access the controlling type variable. But how can I ensure that this variable is defined in the same EBB? Or more importantly, how do I access the list of variables that are within scope of a particular EBB?

**Comment by stoklund** [comment]
Once you have the `typevar_operand()` value, you can find the EBB where it is defined like this:

```rust
let def_ebb = match func.dfg.value_def(typevar_op) {
    ValueDef::Res(inst, _) => func.layout.inst_ebb(inst),
    ValueDef::Arg(ebb,_) => ebb,
}
```
