### ISSUE TITLE
`verify_context()` should also verify CFG integrity

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#67]
The `verifier::verify_context()` function checks that the dominator tree in the context matches a newly computed one. We should do the same thing for the control flow graph.

There is an existing `cfg_integrity` method, but it just checks the just-computed CFG against the function. It doesn't look at the CFG in the context.

cc @angusholder

**Comment by angusholder** [comment]
Should I verify for just the reachable EBBs using `postorder_ebbs()`?

**Comment by stoklund** [comment]
No, I think we can require that the CFG is valid for all EBBs that are in the layout.

**Comment by angusholder** [comment]
Should the postorder be the same between them?

**Comment by stoklund** [comment]
No, the postorder does not have to be the same either.

If you consider the CFG as a *graph*, the two graphs should be equivalent. It should be enough to verify that the predecessor sets are identical *as sets*, and the successor sets are identical *as sets*.

**Comment by angusholder** [comment]
Ok got it, thank you

**Comment by stoklund** [comment]
Fixed by @angusholder in #70.
