### ISSUE TITLE
Verify instruction encodings

### ISSUE THREAD

**Issue by stoklund** [stoklund/cretonne#69]
The verifier #3 can be extended to also verify ISA-dependent properties. We can start with instruction encodings.

# ISA-dependent verification.

The `verify_function()` function should take an additional `isa: Option<&TargetIsa>` argument, like `write_function()` already does. Passing some ISA reference should cause additional ISA-dependent properties to be verified. The ISA-independent properties should be verified no matter what the `isa` argument is.

# Encoding verification.

For all instructions that have a legal encoding in the `func.encodings` table, verify that it is consistent with the encoding chosen by `isa.encode(dfg[inst])`. Use `TargetIsa::display_enc()` to generate pretty error messages.

Instructions that don't have a legal encoding (see `Encoding::is_legal()`) should be ignored. Start by checking `func.encodings.is_empty()`.

**Comment by anholt** [comment]
Thanks for putting up some easy bugs!  I've been interested in a rust implementation of a compiler backend for a while, and I think this might be fun to play with in my free time.

I wrote up an implementation, but test-all.sh isn't calling the verifier with !encodings.is_empty() && isa.is_some() .  Are there existing testcases I'm missing?  Also, is there an IRC channel or similar where people hang out?

**Comment by stoklund** [comment]
Hi @anholt, it would be great if you want to help out! There's no IRC channel, but feel free to file issues, ask questions in comments, or email me directly.

Those test cases in `filetests/isa/riscv` that contain the test command `test legalizer` should be running the verifier after the legalizer with the `encodings` table filled in. The entry point to the verifier is the `Context::verify_if` method in `cretonne/src/context.rs`. The `isa` argument needs to be propagated to the `verify_context()` function.

If you want to write tests for verification failures, it should be possible to write `test verifier` test cases that also contain a `isa riscv` spec and pre-assigned instruction encodings, like in `filetests/isa/riscv/binary32.cton`.

**Comment by anholt** [comment]
Thanks, the verify_context() path was what I needed.  Updated the branch with the series, and now I think it needs tests for the new verification.  Poking at that now.

**Comment by anholt** [comment]
Would you want pre-assigned instruction encodings (`binemit.rs`'s `bin:` comment parsing) to be pulled into `func.encodings[]`, as part of `verifier.rs`?

**Comment by stoklund** [comment]
No, I don't think the verifier should modify anything in the function.

By 'pre-assigned instruction encodings', I meant test input like this:

```
[R#200c]    v11 = isub v1, v2
```

The `[R#200c]` encoding should be mapped to an entry in `func.encodings` for the instruction, and you can change it to something incorrect to make sure the verifier catches it.

See `filetests/parser/instruction_encoding.cton` for an example of that kind of input.

The `bin:` comments are testing the lowest level bits coming out. The `func.encodings` table doesn't have all the information. It doesn't contain information about register operands and branch distances, for example. It's an "encoding recipe", not the complete final binary encoding of the instruction.

The `bin:` comments are beyond the scope of the IL verifier.
