### ISSUE TITLE
Upgrade regex crate in filecheck

### ISSUE THREAD

**Issue by zummenix** [stoklund/cretonne#88]
Currently in `lib/filecheck/Cargo.toml` we have `regex = "0.1.71"`, the plan is:
- replace it by `regex = "0.2.2"`
- `cargo build` and follow-fix compiler errors
- `cargo test` to make sure tests pass

This is a tedious task but suitable for starters as it doesn't require deep knowledge about the project (I think). Also https://github.com/rust-lang/regex/blob/master/CHANGELOG.md can help you.

**Comment by stoklund** [comment]
Sounds good to me! Our use of regular expressions is pretty limited, so this shouldn't be too big a task.
