### ISSUE TITLE
Add documentation link in the readme

### ISSUE THREAD

**Issue by zummenix** [stoklund/cretonne#92]
I didn't know that we have generated documentation: http://cretonne.readthedocs.io/en/latest/
Probably it makes sense to mention it in the readme.

**Comment by sunfishcode** [comment]
The badge at the top of the README that links to "docs latest" does link to the documentation, though it'd be good to do something to make it stand out more, as I've heard from others who have missed this link too.

**Comment by zummenix** [comment]
I missed it too :). Thanks for pointing out.

**Comment by stoklund** [comment]
Patches welcome

**Comment by siriux** [comment]
Is there any API documentation available for cretonne? The linked documentation is really interesting, but it doesn't include the API of the library.

**Comment by sunfishcode** [comment]
For now, you can generate API documentation manually with `cargo doc`.

When the API becomes stablizes more, cretonne will likely be published on crates.io, with the API documentation hosted on docs.rs.

**Comment by sunfishcode** [comment]
The original issue here is now fixed in #171. Please file new issues if there are further questions!
